services:
    pairdesksystem:
        build: pairdesksystem.iml
        hostname: pairdesk-management
        #mem_limit: 350m
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            mysql1:
                condition: service_healthy

    mysql1:
        image: mysql:5.7
        #mem_limit: 350m
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=rootpwd
            - MYSQL_DATABASE=pairdesk-db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pwd
        volumes:
            - ./data/mysql1:/var/lib/mysql1
            - ./data/init.d:/docker-entrypoint-initdb.d
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-uuser",
                    "-ppwd",
                    "-h",
                    "localhost",
                ]
            interval: 10s
            timeout: 5s
            retries: 10

